CREATE TABLE brands (
  brand_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE products (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  price INTEGER,
  discount INTEGER,
  quantity INTEGER,
  description TEXT,
  url TEXT,
  recommended BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  brand_id INTEGER,
  FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE product_images (
  product_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT,
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE product_features (
  product_feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  recommended BOOLEAN,
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE product_feature_values (
  product_feature_value_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value TEXT,
  product_feature_id INTEGER,
  FOREIGN KEY (product_feature_id) REFERENCES product_features(product_feature_id),
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE publications (
  publication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE product_publications (
  product_publication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id INTEGER,
  FOREIGN KEY (publication_id) REFERENCES publications(publication_id),
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE product_recommendations (
  product_recommendation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recommended_product_id INTEGER,
  FOREIGN KEY (recommended_product_id) REFERENCES products(product_id),
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE customers (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  address TEXT,
  postal_code TEXT,
  city TEXT,
  country TEXT,
  phone TEXT,
  oib TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE receipts (
  receipt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  customer_id INTEGER,
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE receipt_products (
  receipt_product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id INTEGER,
  FOREIGN KEY (receipt_id) REFERENCES receipts(receipt_id),
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE offers (
  offer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  customer_id INTEGER,
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE offer_products (
  offer_product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id INTEGER,
  FOREIGN KEY (offer_id) REFERENCES offers(offer_id),
  product_id INTEGER,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE events (
  event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT,
  name TEXT,
  description TEXT,
  device TEXT,
  created_at TIMESTAMP
);